### ISSUE TITLE
I am keen to join your team and utilize my expertise to help achieve outstanding results on your projects.

### ISSUE THREAD

**Issue by johnsmith0212** [Bitcoin-GroupHug/bitcoin-grouphug#1]
Hello, I'm Ethan Tan, a web full-stack and blockchain developer with more than 8 years in the field. I focus on building reliable, scalable web applications and advanced blockchain solutions. Leveraging my knowledge of React.js, Vue.js, and Next.js, combined with my Solidity skills for smart contract development, I provide high-quality, secure, and efficient solutions tailored to your distinct needs.

**Comment by 1ma** [comment]
Thank you for your interest, but we aren't looking for this skillset.

**Comment by johnsmith0212** [comment]
which kind of developer do you looking for?

plz contact me

-Contact Info
skype: https://join.skype.com/invite/FVUI6gLcYgAE
telegram: https://t.me/ethantan1116
slack: https://join.slack.com/t/ksc-xme4972/shared_invite/zt-2ld45idp2-G9HkxP_wX4ctwQshyPM7Ig
discord: https://discord.gg/VxnfdY4bS4
